package com.local.dao.product;

import com.local.model.Product;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

public class ProductDAOMemImpl implements ProductDAO, Serializable {
    @Serial
    private static final long serialVersionUID = -3496610368316822489L;

    private ConcurrentHashMap<Integer, Product> products;
    private AtomicInteger autoGeneratedId;

    public ProductDAOMemImpl() {
        products = new ConcurrentHashMap<>();
        autoGeneratedId = new AtomicInteger(2);
    }

    @Override
    public Product addProduct(Product product) {
        int id = autoGeneratedId.getAndIncrement();
        product.setId(id);
        products.put(id, product);
        return new Product(product);
    }

    @Override
    public void updateProduct(Product product) {
        products.put(product.getId(), product);
    }

    @Override
    public Product getProductById(int id) {
        Product product = products.get(id);
        if(product != null) {
            return new Product(product);
        }
        return null;
    }

    @Override
    public HashSet<Product> getAllProducts() {
        HashSet<Product> newProducts = new HashSet<>();
        for(Product product : products.values()) {
            newProducts.add(new Product(product));
        }
        return newProducts;
    }

    @Override
    public ArrayList<Product> getProductsSortedBySells() {
//        ArrayList<Product> sortedProducts = new ArrayList<>(products.values());
//        sortedProducts.sort(Comparator.comparingInt(Product::getSold));
//        return sortedProducts;
        return null;
    }

    @Override
    public ArrayList<Product> getProductsSortedByCount() {
//        ArrayList<Product> sortedProducts = new ArrayList<>(products.values());
//        sortedProducts.sort(Comparator.comparingInt(Product::getCount));
//        return sortedProducts;
        return null;
    }
}
