package com.local.dao.payment;

import com.local.model.Payment;
import com.local.model.PaymentStatus;
import com.local.model.User;

import java.util.HashSet;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

public class PaymentDAOMemImpl implements PaymentDAO {
    private ConcurrentHashMap<Integer, Payment> payments;
    private AtomicInteger autoGeneratedId;

    public PaymentDAOMemImpl() {
        payments = new ConcurrentHashMap<>();
        autoGeneratedId = new AtomicInteger(1);
    }

    @Override
    public Payment addPayment(Payment payment) {
        int id = autoGeneratedId.getAndIncrement();
        payment.setId(id);
        payments.put(id, payment);
        return new Payment(payment);
    }

    @Override
    public Payment getPendingPayment(User user) {
        Payment payment = payments.searchValues(16, (p) -> p.getUser().getId() == user.getId() && p.getStatus() == PaymentStatus.PENDING ? p : null);
        if(payment != null) {
            return new Payment(payment);
        }
        return null;
    }

    @Override
    public HashSet<Payment> getAllPayments() {
        HashSet<Payment> newPayments = new HashSet<>();
        for(Payment payment : payments.values()){
            newPayments.add(new Payment(payment));
        }
        return newPayments;
    }

    @Override
    public HashSet<Payment> getAllPendingPayments() {
        return getPaymentsByStatus(PaymentStatus.PENDING);
    }

    @Override
    public HashSet<Payment> getAllCancelledPayments(){
        return getPaymentsByStatus(PaymentStatus.CANCELLED);
    }

    private HashSet<Payment> getPaymentsByStatus(PaymentStatus status) {
        HashSet<Payment> searchedPayments = new HashSet<>();
        for(Payment payment : payments.values()) {
            if(payment.getStatus() == status) {
                searchedPayments.add(new Payment(payment));
            }
        }
        return searchedPayments;
    }

    @Override
    public void updatePayment(Payment payment) {
        payments.computeIfPresent(payment.getId(), (k, v) -> {
            v.setAmount(payment.getAmount());
            v.setLastUpdate(payment.getLastUpdate());
            v.setStatus(payment.getStatus());
            return v;
        });
    }
}
