package com.local.dao.user;

import com.local.model.User;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

public class UserDAOMemImpl implements UserDAO {
    private ConcurrentHashMap<Integer, User> users;
    private AtomicInteger autoGeneratedId;

    public UserDAOMemImpl() {
        users = new ConcurrentHashMap<>();
        autoGeneratedId = new AtomicInteger(1);
    }

    @Override
    public void addUser(User user) {
        int id = autoGeneratedId.getAndIncrement();
        user.setId(id);
        users.put(id, user);
    }

    @Override
    public User getUserById(int id) {
        return users.get(id);
    }

    @Override
    public User getUserByUsername(String username) {
        return users.searchValues(16, (user) -> user.getUsername().equals(username) ? user : null);
    }
}
